version: "3"
services:
  db:
    image: postgres:13
    environment:
      - TZ=Australia/Sydney
      - POSTGRES_DB=localdev
      - POSTGRES_PASSWORD=localdev
    volumes:
      - db_pgdata:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    environment:
      - TZ=Australia/Sydney
  todo-api:
    build: todo-api/
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - TZ=Australia/Sydney
      - PORT=8080
  random-r:
    build: randr/
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - TZ=Australia/Sydney
      - PORT=8081
    volumes:
      # - ./data:/share
      - rand_share:/share
  web:
    build: django/
    command: runserver
    volumes:
      - ./django/:/app:delegated
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - TZ=Australia/Sydney
      - REDIS_LOCATION=redis://redis:6379/1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=localdev
      - DB_USERNAME=postgres
      - DB_PASSWORD=localdev
      - LOCK_TIMEOUT=60
      - BLOCK_TIMEOUT=1
    env_file:
      - .env_local
    depends_on:
      - db
      - redis
      - random-api
      - random-r
volumes:
  db_pgdata:
  rand_share:
