version: "3"
services:
  # db:
  #   image: postgres:13
  #   environment:
  #     - TZ=Australia/Sydney
  #     - POSTGRES_DB=localdev
  #     - POSTGRES_PASSWORD=localdev
  #   volumes:
  #     - db_pgdata:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    environment:
      - TZ=Australia/Sydney
  mongo:
    image: mongo:5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=localdev
      - MONGO_INITDB_ROOT_PASSWORD=localdev
      - TZ=Australia/Sydney
    volumes:
      - mongo_data:/data/db
  todoer-api:
    build: todoer_api/
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - TZ=Australia/Sydney
      - PORT=8000
    volumes:
      - ./todoer_api/:/app:delegated

    # env_file:
    #   - .env_local
    # depends_on:
    #   - db
    #   - redis
    #   - random-api
    #   - random-r
volumes:
  db_pgdata:
  mongo_data:

